# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_Id', models.PositiveSmallIntegerField()),
                ('mpesa_code', models.CharField(max_length=20, unique=True)),
                ('date_of_transaction', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('date_of_transaction', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw')], default='DP', max_length=20)),
                ('cost', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpesa.Transaction'),
        ),
    ]
