# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('mpesa_code', models.CharField(max_length=20)),
                ('date_of_transaction', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw')], default='DP', max_length=20),
        ),
    ]
