# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='national_Id',
            new_name='Identification',
        ),
    ]
